# Generated by Django 5.1.2 on 2024-11-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Ünvan')),
                ('message', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Hakkımda',
                'verbose_name_plural': 'Hakkımda',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sertifika Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('date', models.DateField(verbose_name='Verilme Tarihi')),
                ('url', models.URLField(blank=True, verbose_name='Sertifika Linki')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='Tanıtım')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram Linki')),
                ('youtube', models.URLField(blank=True, verbose_name='Youtube Linki')),
                ('tiktok', models.URLField(blank=True, verbose_name='Tiktok Linki')),
                ('pinterest', models.URLField(blank=True, verbose_name='Pinterest Linki')),
                ('behance', models.URLField(blank=True, verbose_name='Behance Linki')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, verbose_name='Okul Adı')),
                ('degree', models.CharField(max_length=100, verbose_name='Derece')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='Alanı')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Proje Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Resim')),
                ('url', models.URLField(blank=True, verbose_name='Proje Linki')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İş Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Yıllık Deneyim')),
                ('related_projects', models.ManyToManyField(blank=True, to='home.project', verbose_name='İlgili Projeler')),
            ],
            options={
                'verbose_name': 'Deneyim',
                'verbose_name_plural': 'Deneyimler',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yetenek Adı')),
                ('level', models.CharField(choices=[('Beginner', 'Başlangıç'), ('Intermediate', 'Orta'), ('Advanced', 'İleri'), ('Expert', 'Uzman')], default='Intermediate', max_length=20, verbose_name='Seviye')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Yıllık Deneyim')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.skill', verbose_name='Üst Yetenek')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ['name'],
            },
        ),
    ]
